#!/usr/bin/env python3
"""Build the static Roblox rankings page.

Roblox public web endpoints do not currently send browser CORS headers for this
use case, so the GitHub Pages site reads a local data.js generated by this
script instead of calling Roblox directly from the browser.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import time
import urllib.parse
import urllib.request
import uuid
from pathlib import Path
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "roblox"
DATA_JS = OUT_DIR / "data.js"
TZ = ZoneInfo("America/Mexico_City")

EXPLORE_API = "https://apis.roblox.com/explore-api/v1/get-sorts"
GAMES_API = "https://games.roblox.com/v1/games"
ICONS_API = "https://thumbnails.roblox.com/v1/games/icons"
USER_AGENT = "roblox-rankings-static/1.0"
TOP_LIMIT = 10
MIN_VOTES_FOR_RATED = 10000


def fetch_json(url: str, *, timeout: float, retries: int) -> dict:
    last_error: Exception | None = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=timeout) as response:
                return json.loads(response.read().decode("utf-8"))
        except Exception as error:  # noqa: BLE001 - network failures should retry broadly.
            last_error = error
            if attempt < retries:
                time.sleep(min(8.0, 0.75 * (attempt + 1) ** 2))
    raise RuntimeError(f"Could not fetch {url}: {last_error}")


def chunks(items: list[int], size: int):
    for index in range(0, len(items), size):
        yield items[index : index + size]


def collect_sort_games(payload: dict) -> tuple[list[dict], list[dict]]:
    games_by_id: dict[int, dict] = {}
    sorts: list[dict] = []
    for sort in payload.get("sorts") or []:
        games = sort.get("games") or []
        sort_games: list[int] = []
        for game in games:
            universe_id = game.get("universeId")
            if not isinstance(universe_id, int):
                continue
            existing = games_by_id.get(universe_id, {})
            merged = {**existing, **game}
            merged.setdefault("sortNames", [])
            display_name = sort.get("sortDisplayName") or sort.get("sortId") or "Discover"
            if display_name not in merged["sortNames"]:
                merged["sortNames"].append(display_name)
            games_by_id[universe_id] = merged
            sort_games.append(universe_id)
        if sort_games:
            sorts.append(
                {
                    "id": sort.get("sortId") or sort.get("id"),
                    "name": sort.get("sortDisplayName") or sort.get("sortId") or "Discover",
                    "count": len(sort_games),
                }
            )
    return list(games_by_id.values()), sorts


def details_for(universe_ids: list[int], *, timeout: float, retries: int) -> dict[int, dict]:
    details: dict[int, dict] = {}
    for batch in chunks(universe_ids, 50):
        query = urllib.parse.urlencode({"universeIds": ",".join(str(item) for item in batch)})
        payload = fetch_json(f"{GAMES_API}?{query}", timeout=timeout, retries=retries)
        for item in payload.get("data") or []:
            if isinstance(item.get("id"), int):
                details[item["id"]] = item
    return details


def icons_for(universe_ids: list[int], *, timeout: float, retries: int) -> dict[int, str]:
    icons: dict[int, str] = {}
    for batch in chunks(universe_ids, 100):
        query = urllib.parse.urlencode(
            {
                "universeIds": ",".join(str(item) for item in batch),
                "size": "512x512",
                "format": "Png",
                "isCircular": "false",
            }
        )
        payload = fetch_json(f"{ICONS_API}?{query}", timeout=timeout, retries=retries)
        for item in payload.get("data") or []:
            if isinstance(item.get("targetId"), int) and item.get("imageUrl"):
                icons[item["targetId"]] = item["imageUrl"]
    return icons


def vote_ratio(up_votes: int, down_votes: int) -> float:
    total = up_votes + down_votes
    return up_votes / total if total else 0.0


def normalize_game(raw: dict, detail: dict, icon: str | None) -> dict:
    universe_id = raw.get("universeId") or detail.get("id")
    root_place_id = raw.get("rootPlaceId") or detail.get("rootPlaceId")
    up_votes = int(raw.get("totalUpVotes") or 0)
    down_votes = int(raw.get("totalDownVotes") or 0)
    player_count = int(raw.get("playerCount") or detail.get("playing") or 0)
    creator = detail.get("creator") or {}
    canonical_path = detail.get("canonicalUrlPath") or f"/games/{root_place_id}"
    rating = vote_ratio(up_votes, down_votes)
    maturity = raw.get("contentMaturity") or ""
    maturity_label = raw.get("ageRecommendationDisplayName") or maturity.title() or "Sin clasificar"

    return {
        "universeId": universe_id,
        "rootPlaceId": root_place_id,
        "name": raw.get("name") or detail.get("name") or "Untitled",
        "description": detail.get("description") or "",
        "creatorName": creator.get("name") or "",
        "creatorType": creator.get("type") or "",
        "playerCount": player_count,
        "visits": int(detail.get("visits") or 0),
        "favorites": int(detail.get("favoritedCount") or 0),
        "upVotes": up_votes,
        "downVotes": down_votes,
        "voteCount": up_votes + down_votes,
        "rating": round(rating * 100, 2),
        "ratingPretty": f"{rating * 100:.1f}%",
        "maxPlayers": int(detail.get("maxPlayers") or 0),
        "created": detail.get("created") or "",
        "updated": detail.get("updated") or "",
        "genre": detail.get("genre") or "All",
        "maturity": maturity,
        "maturityLabel": maturity_label.replace("Maturity: ", ""),
        "sortNames": raw.get("sortNames") or [],
        "icon": icon or "",
        "robloxUrl": f"https://www.roblox.com{canonical_path}",
    }


def top_active(games: list[dict]) -> list[dict]:
    return sorted(games, key=lambda item: (-item["playerCount"], -item["visits"], item["name"]))[:TOP_LIMIT]


def top_rated(games: list[dict]) -> list[dict]:
    eligible = [item for item in games if item["voteCount"] >= MIN_VOTES_FOR_RATED]
    if len(eligible) < TOP_LIMIT:
        eligible = [item for item in games if item["voteCount"] > 0]
    return sorted(
        eligible,
        key=lambda item: (
            -item["rating"],
            -math.log10(item["voteCount"] + 1),
            -item["playerCount"],
            item["name"],
        ),
    )[:TOP_LIMIT]


def top_favorites(games: list[dict]) -> list[dict]:
    return sorted(games, key=lambda item: (-item["favorites"], -item["playerCount"], item["name"]))[:TOP_LIMIT]


def maturity_options(games: list[dict]) -> list[dict]:
    seen: dict[str, str] = {}
    for game in games:
        key = game.get("maturity") or "unknown"
        seen.setdefault(key, game.get("maturityLabel") or key.title())
    ordered = [{"id": "all", "label": "Todas"}]
    for key in sorted(seen, key=lambda item: (item == "unknown", seen[item])):
        ordered.append({"id": key, "label": seen[key]})
    return ordered


def by_maturity(games: list[dict], selector) -> dict[str, list[dict]]:
    output = {"all": selector(games)}
    for option in maturity_options(games):
        if option["id"] == "all":
            continue
        selected = [game for game in games if (game.get("maturity") or "unknown") == option["id"]]
        output[option["id"]] = selector(selected)
    return output


def build_payload(args: argparse.Namespace) -> dict:
    session_id = str(uuid.uuid4())
    explore_url = f"{EXPLORE_API}?{urllib.parse.urlencode({'sessionId': session_id})}"
    payload = fetch_json(explore_url, timeout=args.timeout, retries=args.retries)
    raw_games, sorts = collect_sort_games(payload)
    universe_ids = sorted({int(game["universeId"]) for game in raw_games if isinstance(game.get("universeId"), int)})
    detail_map = details_for(universe_ids, timeout=args.timeout, retries=args.retries)
    icon_map = icons_for(universe_ids, timeout=args.timeout, retries=args.retries)

    games = [
        normalize_game(raw, detail_map.get(int(raw["universeId"]), {}), icon_map.get(int(raw["universeId"])))
        for raw in raw_games
    ]
    games = [game for game in games if game.get("universeId") and game.get("rootPlaceId")]

    return {
        "generatedAt": dt.datetime.now(tz=TZ).isoformat(timespec="seconds"),
        "source": "Roblox public web APIs",
        "sessionId": session_id,
        "stats": {
            "sampleSize": len(games),
            "totalPlayers": sum(game["playerCount"] for game in games),
            "totalVisits": sum(game["visits"] for game in games),
            "totalFavorites": sum(game["favorites"] for game in games),
            "minVotesForRated": MIN_VOTES_FOR_RATED,
        },
        "sorts": sorts,
        "maturityOptions": maturity_options(games),
        "topActive": top_active(games),
        "topActiveByMaturity": by_maturity(games, top_active),
        "topRated": top_rated(games),
        "topRatedByMaturity": by_maturity(games, top_rated),
        "topFavorites": top_favorites(games),
        "topFavoritesByMaturity": by_maturity(games, top_favorites),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Update Roblox static rankings data")
    parser.add_argument("--timeout", type=float, default=20.0)
    parser.add_argument("--retries", type=int, default=4)
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    payload = build_payload(args)
    DATA_JS.write_text(
        "window.ROBLOX_DASHBOARD_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "sampleSize": payload["stats"]["sampleSize"],
                "topActive": [game["name"] for game in payload["topActive"][:3]],
                "topRated": [game["name"] for game in payload["topRated"][:3]],
                "topFavorites": [game["name"] for game in payload["topFavorites"][:3]],
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
